apiVersion: v1
kind: Secret
metadata:
  name: eks-assignment-secret
  namespace: eks-assignment
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:changeme@localhost:5432/dbname"
  API_KEY: "changeme"
  NODE_ENV: "production"
