apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-assignment-sa
  namespace: eks-assignment
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/eks-assignment-app-role
